from .menu import *
from .schedule import *
from .subscribe import *
from .info import *
from .middleware import *
from .rings import *
from .holidays import *
from .weather import *
from .teacher import *
from .admin import *
from .not_found import *